# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-16 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='show_price',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u53ef\u67e5\u770b\u4ef7\u683c'),
        ),
    ]
