# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-30 23:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=64, unique=True, verbose_name='\u54c1\u724c')),
                ('in_stock', models.BooleanField(default=True, verbose_name='\u662f\u5426\u4e0a\u67b6')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u54c1\u724c',
                'verbose_name_plural': '\u54c1\u724c',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64, unique=True, verbose_name='\u54c1\u7c7b')),
                ('in_stock', models.BooleanField(default=True, verbose_name='\u662f\u5426\u4e0a\u67b6')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u54c1\u7c7b',
                'verbose_name_plural': '\u54c1\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='\u6807\u4ef7')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='\u6570\u91cf')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('remarks_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='JSON\u5907\u6ce8')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5e93\u5b58',
                'verbose_name_plural': '\u5e93\u5b58',
            },
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24, unique=True, verbose_name='\u5546\u54c1\u7f16\u7801')),
                ('in_stock', models.BooleanField(default=True, verbose_name='\u662f\u5426\u4e0a\u67b6')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Brand', verbose_name='\u54c1\u724c')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Category', verbose_name='\u54c1\u7c7b')),
            ],
            options={
                'verbose_name': '\u5546\u54c1',
                'verbose_name_plural': '\u5546\u54c1',
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='merchandise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Merchandise', verbose_name='\u5546\u54c1'),
        ),
    ]
