# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-23 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='after_sales',
            field=models.SmallIntegerField(default=1, verbose_name='\u552e\u540e\u670d\u52a1'),
        ),
        migrations.AddField(
            model_name='merchandise',
            name='certification',
            field=models.CharField(default='\u65e0', max_length=36, verbose_name='\u8ba4\u8bc1'),
        ),
        migrations.AddField(
            model_name='merchandise',
            name='delivery_time',
            field=models.SmallIntegerField(default=3, verbose_name='\u5305\u88c5\u914d\u4ef6'),
        ),
        migrations.AddField(
            model_name='merchandise',
            name='model',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='\u5546\u54c1\u578b\u53f7'),
        ),
        migrations.AddField(
            model_name='merchandise',
            name='spare_parts',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5305\u88c5\u914d\u4ef6'),
        ),
    ]
