# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-24 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_add_new_fields_of_merchandise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='remarks_json',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='\u5e93\u5b58\u5907\u6ce8'),
        ),
    ]
