# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-11-23 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20190325_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='spare_parts',
            field=models.TextField(blank=True, null=True, verbose_name='\u5c5e\u6027'),
        ),
    ]
