# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-12-15 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventory_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchandise',
            name='delivery_time',
        ),
    ]
