# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-12-23 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_merchandise_delivery_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchandise',
            name='after_sales',
        ),
    ]
