# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-01-04 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_merchandise_after_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='code',
            field=models.CharField(max_length=64, unique=True, verbose_name='\u5546\u54c1\u7f16\u7801'),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='model',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='\u5546\u54c1\u578b\u53f7'),
        ),
    ]
