# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-24 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_auto_20190324_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, '\u5b58\u5165'), (1, '\u81ea\u53d6\u51fa'), (2, '\u8c03\u914d')], default=0, verbose_name='\u53d8\u52a8\u7c7b\u578b')),
                ('initiator', models.UUIDField(verbose_name='\u53d1\u8d77\u5546\u6237')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='\u53d8\u52a8\u6570\u91cf')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='\u65f6\u4ef7')),
                ('deal_price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='\u6210\u4ea4\u4ef7')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Inventory', verbose_name='\u53d8\u52a8\u5e93\u5b58')),
            ],
            options={
                'verbose_name': '\u8bb0\u5f55',
                'verbose_name_plural': '\u8bb0\u5f55',
            },
        ),
    ]
