# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-25 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': '\u5e93\u5b58\u8bb0\u5f55', 'verbose_name_plural': '\u5e93\u5b58\u8bb0\u5f55'},
        ),
    ]
