# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-11 17:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20190325_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u53d1\u8d77\u5546\u6237'),
        ),
    ]
