# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-11 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_history_prev_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='prev_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='\u539f\u5e93\u5b58\u6570\u91cf'),
        ),
    ]
