# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-12-14 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_auto_20190411_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='\u4f9b\u8d27\u4fe1\u606f'),
        ),
    ]
